name:                ad-on-higher-order-functions
version:             0.1.0.0
github:              "PhiliPdB/ad-on-higher-order-functions"
license:             BSD3
author:              "Philip de Bruin, Pieter Knops, Danny de Jong"
maintainer:          "Philip de Bruin <p.debruin@students.uu.nl>, Pieter Knops <p.d.knops@students.uu.nl>, Danny de Jong <g.j.dejong2@students.uu.nl>"
copyright:           "2021 Philip de Bruin, Pieter Knops, Danny de Jong"

extra-source-files:
- README.md

description:         Please see the README <https://github.com/PhiliPdB/ad-on-higher-order-functions/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
  - vector-sized
  - mtl
  - ghc-typelits-natnormalise
  - containers
  - some
  - tasty
  - tasty-quickcheck

tests:
  ad-test:
    main: test/Main.hs
    dependencies:
    - ad-on-higher-order-functions
    ghc-options:
    - -O2 -threaded -rtsopts "-with-rtsopts=-qg -N4 -A10M"
