name:                ad-on-higher-order-functions
version:             0.1.0.0
github:              "PhiliPdB/ad-on-higher-order-functions"
license:             BSD3
author:              "Philip de Bruin, Pieter Knops, Danny de Jong"
maintainer:          "Philip de Bruin <p.debruin@students.uu.nl>, Pieter Knops <p.d.knops@students.uu.nl>, Danny de Jong <g.j.dejong2@students.uu.nl>"
copyright:           "2021 Philip de Bruin, Pieter Knops, Danny de Jong"

extra-source-files:
- README.md
- Examples.hs

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README <https://github.com/PhiliPdB/ad-on-higher-order-functions/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- vector-sized
- mtl
- ghc-typelits-natnormalise
- containers

ghc-options:
- -Wall

library:
  source-dirs: src
