name:                CHAD
version:             0.1.0.0
github:              "VMatthijs/CHAD"
license:             BSD3
author:              "CHAD Contributors"
maintainer:          "Tom Smeding <t.j.smeding@uu.nl>, Matthijs V치k치r <m.i.l.vakar@uu.nl"
copyright:           "2021 Philip de Bruin, Pieter Knops, Danny de Jong, Tom Smeding, Matthijs V치k치r"

extra-source-files:
- README.md

description:         Please see the README

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
  - vector-sized
  - mtl
  - ghc-typelits-natnormalise
  - containers
  - some
  - tasty
  - tasty-quickcheck

tests:
  ad-test:
    main: test/Main.hs
    dependencies:
    - ad-on-higher-order-functions
    ghc-options:
    - -O2 -threaded -rtsopts "-with-rtsopts=-qg -N6 -A10M"
